[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
twopart = "8Pq7ktrXscMpnabgCLXzqyv1iv2wWy8mTg8JSYYW4oFa"
geographical = "2X76PnikUodN6mVYFUUGQegXvctXefWcexkJJGpWgKyi"
seasonal_inc = "ArBfA7Qd6t33oKiWsdFc7RxTzECzfEC3BHgmmKvZxqNQ"
seasonal_dec = "ASENYNUVWkTCiEfKCiyZiBKXxRkcEfCCL7jWGgRDcpnY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
