[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
aquachain = "62BMhEVwxxV1RQjd9rxgyhW8ebvyxiDfRDbZRxERw8yC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
populateLocalnet = "npx ts-node scripts/populateLocalnet.ts"
